# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: &defaults
  adapter: postgresql
  database: ladder_devel
  username: pablobm
  password:
  host: 127.0.0.1
  encoding: utf8
